nonmilk/coffee-grinder

- lib/build.gradle.kts
- lib/src/main/java/module-info.java
add all initial needed dependencies for the project.
the https://github.com/traunin/triangulation at v1.0.1 doesn't contain the module-info, so it was marked as TODO.
> build: initial module-info and build script

- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraMatrix.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicCamera.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveCamera.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/view/OrthographicView.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/view/PerspectiveView.java
instead of writing the same code twice and relying too much on camera classes, make views as separate entities with their own parameter handling.
> feat/camera: views

- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Camera.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraMatrix.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/ClippingBox.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicCamera.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveCamera.java
1. move to correct package
2. make method names more concise
3. use correct exceptions
4. make use of composition correctly as a reference
> feat/clipping-box: refactor

- .idea/.gitignore
- .idea/compiler.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- .idea/vcs.xml
Config for IntelliJ IDEA users (couldn't be me lol)
> chore: IDEA config

- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraOrientation.java
follow-up to #7.
style some parts and add missing check on setters.
> feat/camera-orientation: style and setters

- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Camera.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraMatrix.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraOrientation.java
Part of a refactor to use composition across-the-board
> refactor(camera)!: make CameraOrientation a class

- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicCamera.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveCamera.java
This fixes the camera's view matrix, which was previously calculated incorrectly
> fix: correct view matrix

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
Handles polygon rotation edge cases
> fix: handling polygons parallel to XY

- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ZBuffer.java
Z-buffer to store pixels closest to camera and not draw over them
> feat: implement z-buffer

- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec3f.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedTriangle.java
WIP pull as I don't yet know what I'll need for rasterization
> feat: TexturedTriangle basic setup

- lib/src/main/java/module-info.java
Make some libraries available to users as transitive dependencies
> build: transitive dependencies

- lib/src/main/java/module-info.java
1. correct package path
2. refactor dependencies
> build: fix module-info

- lib/build.gradle.kts
- lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
with the bump use the new features (only `vertex.clear()` for now) and do some styling
> chore: bump jshaper to 0.10.2

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
> refactor: remove unused

- lib/build.gradle.kts
- lib/src/main/java/module-info.java
the description can be viewed in commit messages
> build: sync with module-info

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Floats.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/UnitVec3f.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/RenderedFace.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Lighting.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Normal.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Positioning.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Shape.java
Refactor to split TexturedTriangle (now called Rendered face) into separate classes
> refactor!: rename Positioning to Shape

- lib/build.gradle.kts
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/AffineTransformation.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/DataList.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Rotator.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Scaling.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Transformation.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Translator.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/package-info.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
- lib/src/main/java/module-info.java
Affine library from `.jar` moved into src code as `*.java` files
> feat: affine library

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ColorTexture.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/RenderedFace.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Texture.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/UV.java
- lib/src/main/java/module-info.java
> style: remove tab

- lib/build.gradle.kts
- lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec3f.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec4f.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ColorTexture.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/RenderedFace.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Texture.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Normal.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Shape.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/UV.java
latest versions as of 2025-01-01
> chore: bump dependencies

- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
Correctly set camera's coordinate system
> fix: normalize camera x

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Scene.java
because multiple cameras are not needed in the library itself, it is expected to handle multiple cameras on user level
> feat(Scene)!: remove camera list

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Scene.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ScreenTransform.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
Move entities related only to rasterization to RenderingPipeline
> refactor: move lighting to scene

- lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/RotationOrder.java
JavaDocs for Transformation system
> docs(transformations): add docs

- lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/RotationOrder.java
First of all, it is needed to close pull request #31.
Then notify if there were any changes or close this pull request.
> fix(model transformer): remove issues in methods implementation

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Mesh.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/MeshFace.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/RenderedFace.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Normal.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Shape.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/UV.java
Move triangulation-related things into mesh
> refactor: use compatible structure

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
- model() -> obj()
- modelMatrix() -> matrix()
> refactor(Model)!: change method signatures

- lib/build.gradle.kts
- lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Normal.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
* Connect transform functionality to `Model` by passing transformation object to the special `::transform(ModelTransformer)` method, which changes modelMatrix inside it.
* New version of linear-algebra library with optimized matrix-vector product.
* Some side changes in `Model` class.
> feat(transforms): transform functionality in model

- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
everything is described in commit's descriptions
> refactor!: ImageTexture rework

- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
> refactor: remove unnecessary floor

- lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
Got to also fix it in frontend
> fix: correct orientation in space

- lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Rotator.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
new getters
remove relative setters
> feat(model transformer): upd api

- lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
I hate this, but in the current rasterization implementation it's more or less the only way
> feat: clip when dimensions exceed allowed

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Shape.java
It currently doesn't take z-buffer into account, but I think I have a fix
> feat: vertex selection

- lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
regenerate the zbuffer based on screen width and height
> fix: adapt to screen

- lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
- lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Wireframe.java
> feat: expose rendering settings
